### ISSUE TITLE
[pythonhead] A tutorial for python, Phase Two

### ISSUE THREAD

**Issue by li012589** [mjtian/cycleNormalizingFlow#10]
Plz see https://github.com/mjtian/cycleNormalizingFlow/blob/dev2/pythonhead/test.md and https://github.com/mjtian/cycleNormalizingFlow/blob/dev2/pythonhead/test.py for details. Fill all <_> in test.py and make it runs without error.

**Comment by mjtian** [comment]
I fill most of it in branch dev2, you can checkout there to have a look.
