### ISSUE TITLE
[pythonhead] A tutorial for python, Phase One

### ISSUE THREAD

**Issue by li012589** [mjtian/cycleNormalizingFlow#6]
Here's some simple python tutorial for you, have fun!

This is the same as in git tutorial, I have created a folder named "pythonhead", all operators should happen there.
- [x] **Hello World from Python** write a python script that prints "hello world!", this script should be called "hello.py";

- [x] **Hello World from Numpy** write a python script using numpy that generate two random matrices from Gaussian distribution, and do matrix multiplication on this two matrices, print the result.  This script should be called "helloNumpy.py";
**Ref**: [numpy.random.randn](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html);[numpy.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html);

- [x] **Hello World from pytorch** write a python script using pytorch that generate two random matrices from Gaussian distribution, and do matrix multiplication on this two matrices, print the result.(*THE SAME TASK AS ABOVE*) This script should be called "helloPytorch.py";
**Ref**: [pytorch docs](https://pytorch.org/docs/stable/index.html). *DO THE SEARCH YOURSELF THIS TIME!* note that search bar can found at the left, and the function names are *NOT* exactly the same between pytorch and numpy! 

- [x] **Hello World from pytorch with love of backward** write a python script using pytorch that do a scalar calculation like y = k*x, and get the grad of y w.r.t x, this should be k. This script should be called "helloBack.py";
**Ref**: [pytorch tutorial](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py);

- [x] **Hello World from pytorch and numpy combined** write a python script using both numpy and pytorch, generate a vector from pytorch using variables from Gaussian distribution, and generate a matrix in numpy using variables from Gaussian distribution. Do the matrix multiplication in both pytorch and numpy(you need to know how to convert variables between this two). Compare two results(using assert_array_almost_equal from numpy.testing).This script should be called "helloBoth.py";
**Ref** [numpy.testing.assert_array_almost_equal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_array_almost_equal.html)

**Comment by mjtian** [comment]
have a talk about the precision of numpy array and tensor

**Comment by li012589** [comment]
About task5 you should use assert from numpy.testing to do the check of these two results be the same. @mjtian

**Comment by mjtian** [comment]
is it right now?

**Comment by li012589** [comment]
Yeah, code works. But I made some minor change to show you how usually assert works.
