### ISSUE TITLE
[gitaround] A tutorial for git, Phase Two

### ISSUE THREAD

**Issue by li012589** [mjtian/cycleNormalizingFlow#7]
- [x] **Diff:** `git diff <A> <B>` can show you difference between two branches/commits, you can try: `git diff ^HEAD`, here ^ means the former one, and HEAD means the commit you are currently at, so ^HEAD means the commit before currently, and if `<B>` is not provided, it is defaultly HEAD. So this gives you differences between former and current commit. Also try `git diff dev`, if you are in master this give you differences between master branch and dev branch.

- [x] **Pull/Fetch:** In newer version of git, `git pull`, `git fetch` do almost the same thing, by definition `fetch` only fetch info from reomte host and don't download while `pull` download what new at host. I have created a new branch in this repo called "dev2", your task is pull it to your machine and commit a file called "foundit" in this branch.

- [x] **Conflict&Merge auto:** `git merge <branch> ` will try to merge the branch provided with currently branch you are in, try merge dev with master, this will trigger *auto merge*, everything will be automatically figured out by git. And then del remote dev branch in this repo: try `git push -d origin dev` and open github you will find this dev branch has been deleted.

- [x] **Conflict&Merge manual:** TELL ME WHEN YOU ARE HERE! I will create some conflicts that can not be auto merged, and you can try to merge these conflicts. 
**In practice** when you merge you just merge, git will tell you if it can't auto merge for you then you resolve these conflicts.

For now, tutorial of git is done. You should feel much confident around git.

**Comment by mjtian** [comment]
I can't find dev2

**Comment by li012589** [comment]
By the way, `git branch` gives your all branch local and remote.@mjtian

**Comment by li012589** [comment]
@mjtian Now plz **DON'T** pull. First at branch dev, change the context of `gitaround/Hello.md` from `hello from another dimension!` to just `Hello world!` and add & commit. Then you can pull, and a conflict will happen and you can try to fix it. Have fun!

**Comment by mjtian** [comment]
emmmm maybe i'm wrong
